select user();
select * from from_py.cust;
use from_py;

alter table cust 
rename column `purchase_amount_(usd)` to purchase_amount_usd;


-- Q1. What is the total revenue generated by male vs. female customers?

select distinct gender from cust;

select gender, sum(purchase_amount_usd) as total_revenue_by_gender
from cust group by 1;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount_usd from cust 
where lower(discount_applied) ='yes' and  purchase_amount_usd > (select avg(purchase_amount_usd) from cust c );


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as avg_rating
from cust 
group by 1 
order by 2 desc 
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,avg(purchase_amount_usd)
from cust 
where shipping_type in ('Standard', 'Express')
group by 1;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status ,
count(customer_id) as total_customers, avg(purchase_amount_usd) as average_spend,  sum(purchase_amount_usd) as total_revenue 
from cust 
group by 1
order by 3 desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

-- (This also answer question: For which products do customers mostly buy only when a discount is available?

select item_purchased, 
100 * sum(case when discount_applied  = 'yes' then 1 else 0 end)/count(*)  as discount_applied
from cust
group by 1
order by 2 desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with cte as (
select previous_purchases, 
case when previous_purchases =1 then 'New' 
when previous_purchases >1 and previous_purchases <=10 then 'Returning'
else 'Loyal'
end as segment
from cust )
select segment , count(*) as number_of_customer
from cte 
group by 1
order by 2 desc;

-- Q8. What are the top 3 most purchased products within each category? 

with cte as (
select category, item_purchased , count(*) as total
from cust 
group by 1 ,2
),
cte2 as (
select category, item_purchased, rank() over(partition by category order by total desc) as rnk
from cte
)
select category, item_purchased 
from cte2
where rnk in (1,2,3)
order by category, rnk desc;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM cust
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group , 100 * sum(purchase_amount_usd)/ sum(sum(purchase_amount_usd)) over() as `%contribution`
from cust
group by 1